### ISSUE TITLE
Converters don't work with newly added dates

### ISSUE THREAD

**Issue by grzesiek2010** [medic/bikram-sambat#12]
Pr https://github.com/medic/bikram-sambat/pull/10 has been merged adding more dates.
Unfortunately, converters don't work with those dates.

**BsCalendar.getInstance().toBik()** throws an expception:
`bikramsambat.BsException: Date outside supported range:`

and **BsCalendar.getInstance().toGreg()** returns year 1950 for all newly added years.

@garethbowen

**Comment by garethbowen** [comment]
@grzesiek2010 I added a couple of unit tests for these functions both of which work as expected. Can you give a couple of examples of specific dates you're using that give these responses?

**Comment by grzesiek2010** [comment]
each of newly added eg:
BsCalendar.getInstance().toBik(1949, 6, 6);
and
BsCalendar.getInstance().toGreg(new BikramSambatDate(1930, 1, 21));

**Comment by garethbowen** [comment]
Thanks - having a look now.

**Comment by garethbowen** [comment]
@grzesiek2010 

The earliest supported date is 1970-01-01 BS so your second test should be throwing an exception. I've got a failing unit test now so I'll get that to throw an exception instead of returning an incorrect date. Could you please try a supported date? eg:

```java
BsCalendar.getInstance().toGreg(new BikramSambatDate(1970, 1, 21));
```

**Comment by grzesiek2010** [comment]
Sorry I made a mistake... you can put there even 1980:
`BsCalendar.getInstance().toGreg(new BikramSambatDate(1980, 1, 21));`
it returs 1950 anyway.

**Comment by garethbowen** [comment]
Is it possible you're running the old jar (v1.0.0)? 1950 was the _old_ epoch so that would be returned if using v1.0.0. I'll check the published jar and make sure the 1.1.0 version is correct.

**Comment by garethbowen** [comment]
When I decompile the published v1.1.0 jar the code is up to date with the source in the repo so I'm confident it's updated. When I run all your tests locally they pass. Please double check that you're including the v1.1.0 jar and then we can decide on the next steps from there.

**Comment by grzesiek2010** [comment]
Yes I've been using 
` implementation 'bikramsambat:bikram-sambat:1.1.0'`
since you announced it.
but now when I started tests again they look better did you change anything?

**Comment by grzesiek2010** [comment]
I'll add some tests and let you know if it works well.

**Comment by garethbowen** [comment]
I haven't touched anything. Maybe there was a jar caching issue or something? Anyway, glad to hear it's working pending further tests.

I've added a few tests and made the change which throws an exception when given an invalid date. Let me know if the exception throwing code deserves another release.

**Comment by grzesiek2010** [comment]
Thanks. Seems to be fine now. I don't know what was wrong...
