### ISSUE TITLE
Support more dates (eg. <1950)

### ISSUE THREAD

**Issue by grzesiek2010** [medic/bikram-sambat#8]
I work as an Android developer on [ODK Collect](https://github.com/opendatakit/collect) where we use this project.
Recently one of our users wanted to use not supported dates <1950
https://forum.opendatakit.org/t/bikram-sambat-nepali-date-widget/16844

Is it possible to support more dates?

**Comment by grzesiek2010** [comment]
@alxndrsn would you be able to do that?

**Comment by alxndrsn** [comment]
Hi @grzesiek2010, I'll try to get data for extending the supported date range.

**Comment by alxndrsn** [comment]
Fix https://github.com/medic/bikram-sambat/issues/9 and once confirmed that our current data agrees with https://github.com/bahadurbaniya/Date-Converter-Bikram-Sambat-to-English-Date, extend using the month-length values from that implementation: no other source of month length data has been found.

**Comment by naveagar** [comment]
Is that solved?

**Comment by garethbowen** [comment]
@naveagar Not yet. I'm going to try and get to it this week.

**Comment by naveagar** [comment]
@garethbowen will be very helpful as Nepal is going to implement this widget by 1 Feb, if worked, otherwise, have to use English Cal. Thank you so much in advance.

**Comment by garethbowen** [comment]
@naveagar @grzesiek2010 I think this is now fixed. I've released v1.1.0 of the jar to the maven repo, and v1.6.0 of the js library and v1.5.0 of the bootstrap plugin to npm. Let me know if you have any issues!

**Comment by naveagar** [comment]
@garethbowen Thanks a lot. Someone has to now update ODK, so that I can update my app.

**Comment by grzesiek2010** [comment]
@garethbowen Thanks a lot! I've just created a pr https://github.com/opendatakit/collect/pull/2814

@naveagar we are going to release v1.19.0 next week so hopefully that pr will be included.

**Comment by alxndrsn** [comment]
@garethbowen has this been released to Maven Central, or still in https://staging.dev.medicmobile.org/_couch/maven-repo?

**Comment by garethbowen** [comment]
It's still in staging.dev. It'd be good to move it to maven central some time.

**Comment by naveagar** [comment]
Any idea, when the v1.19.0 (with Bikram Sambat) will get released?

**Comment by naveagar** [comment]
@grzesiek2010 
Thanks for providing beta version,I have tested Nepali calendar and it is working fine now. Is this apk has any other update apart from Nepali calendar? I can use this apk also but I wonder if this has been tested for any other changes or not.

if it could be little then 3-Feb then would be better, as the team will be deployed from 4th Feb and need some time to setup the devices.

**Comment by grzesiek2010** [comment]
@naveagar 
I would rather recommend using the app from the Play Store. @yanokwa what do you think? Maybe we can release on Saturday?
